apiVersion: v1
kind: Secret
metadata:
  name: bankapp-db-secret
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: YWRtaW4xMjM=
  DB_NAME: Y3VzdG9tZXJz
Config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
data:
  DB_HOST: mysqldb
  DB_PORT: "3306"
